name: Conditional-workflow
on: [push]
jobs:
  hello-world:
    if: github.repository == 'git@github.com:selvamsekar66/GH200-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run:  echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run:  echo "Goodbye Moon!"